name: aptos_sdk_dart
description: Aptos SDK
version: 1.0.1
homepage: "https://github.com/banool/aptos_sdk_dart"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  aptos_api_dart: ^1.0.0
  built_collection: ^5.1.1
  built_value: ^8.4.1
  convert: ^3.0.2
  dio: ^4.0.6
  pinenacl: ^0.3.4
  sha3: ^0.2.0
  one_of: ^1.5.0
  one_of_serializer: ^1.5.0

dev_dependencies:
  curl_logger_dio_interceptor:
    # I use this because it lets you set the function used for logging / printing.
    git:
      url: https://github.com/hieubui2409/curl_logger_dio_interceptor.git
      ref: 8ff34b55577083333ab25651335b278192c998e7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
