name: aptos_sdk_dart
description: Aptos SDK
version: 1.1.1
homepage: "https://github.com/banool/aptos_sdk_dart"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  aptos_api_dart: ^1.1.1
  built_collection: ^5.1.1
  built_value: ^8.4.1
  convert: ^3.0.2
  dio: ^5.0.3
  pinenacl: ^0.5.1
  sha3: ^0.2.0
  one_of: ^1.5.0
  one_of_serializer: ^1.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
